#ifndef VTKPVCLIENTSERVERCORERENDERING_EXPORT_H
#define VTKPVCLIENTSERVERCORERENDERING_EXPORT_H

#if defined(WIN32)
#if defined(VTKPVCLIENTSERVERCORERENDERING_EXPORTS)
#define	VTKPVCLIENTSERVERCORERENDERING_EXPORT _declspec(dllexport)
#else
#define	VTKPVCLIENTSERVERCORERENDERING_EXPORT _declspec(dllimport)
#endif // defined(VTKPVVTKEXTENSIONSRENDERING_EXPORTS)
#else	
#define VTKPVCLIENTSERVERCORERENDERING_EXPORT
#endif // defined(VTKPVCLIENTSERVERCORERENDERING_EXPORT)


#endif
