
#ifndef VTKPVVTKEXTENSIONSRENDERING_EXPORT_H
#define VTKPVVTKEXTENSIONSRENDERING_EXPORT_H

#if defined(WIN32)
#if defined(VTKPVVTKEXTENSIONSRENDERING_EXPORTS)
#define	VTKPVVTKEXTENSIONSRENDERING_EXPORT _declspec(dllexport)
#else
#define	VTKPVVTKEXTENSIONSRENDERING_EXPORT _declspec(dllimport)
#endif // defined(VTKPVVTKEXTENSIONSRENDERING_EXPORTS)
#else	
#define VTKPVVTKEXTENSIONSRENDERING_EXPORT
#endif // defined(VTKPVVTKEXTENSIONSRENDERING_EXPORT)

#endif
